name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: step-security/wait-for-secrets@v1
        id: wait-for-secrets
        with:
        #   slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          secrets: |
            LIBAPPS_MFA_TOKEN:
              name: 'LibApps MFA Token'
              description: 'Check email for the token.'

      - run: |
          echo ${{ steps.wait-for-secrets.outputs.LIBAPPS_MFA_TOKEN }}
